" appearence
se guifont=Terminus\ 8
se go=agirLtc
se ruler
se nu
colorscheme zenburn

syntax on

set autoread

" leader
let mapleader = ","
let g:mapleader = ","

" common cmd shortcuts
nmap <leader>e :e<space>
nmap <leader>w :w!<cr>
nmap <leader>q :q<cr>
nmap <leader>Q :qa<cr>
" save file with root permissions"
nmap <leader>W :%!sudo tee > /dev/null %<CR>

" vimrc
map <leader>rc :tabe ~/.vimrc<cr>
autocmd! bufwritepost .vimrc source ~/.vimrc

" default indent
set tabstop=2
set shiftwidth=2
set autoindent

" scrolloff
set scrolloff=100
set sidescrolloff=10


" unprintable chars
set list
set listchars=tab:·\ ,trail:·,extends:→,precedes:←,nbsp:×

" Don't skip wrap lines
noremap j gj
noremap k gk

" K to split
" Basically this splits the current line into two new ones at the cursor position,
" then joins the second one with whatever comes next.
" Especially useful for adding items in the middle of long lists/tuples in Python
" while maintaining a sane text width.
nnoremap K <nop>
nnoremap K h/[^ ]<cr>"zd$jyyP^v$h"zpJk:s/\v +$//<cr>:noh<cr>j^

" tabs
map <leader>tn :tabnew<cr>
map <leader>te :tabedit<space>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove<space>
map <M-l> gt
map! <M-l> <Esc>gt
map <M-h> gT
map! <M-h> <Esc>gT

" buffers
nmap <leader>d :bd<cr>
nmap <leader>D :bd!<cr>

" moving btw windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" <leader>cd switches to the directory of the current buffer
map <leader>cd :cd %:p:h<cr>

" move text with ALT+[jk]
nmap <M-j> mz:m+<cr>`z
nmap <M-k> mz:m-2<cr>`z
vmap <M-j> :m'>+<cr>`<my`>mzgv`yo`z
vmap <M-k> :m'<-2<cr>`>my`<mzgv`yo`z

" search options
set incsearch
set ignorecase
set smartcase
set hlsearch

" cursor hiliting
set cursorcolumn
set cursorline

" completeion
inoremap <c-space> <c-x><c-n>
set completeopt=menu,longest
" supertab
let g:SuperTabDefaultCompletionType = "<c-x><c-o>"
let g:SuperTabMidWordCompletion = 0
let g:SuperTabLongestEnhanced = 1
let g:SuperTabLongestHighlight = 1
let g:SuperTabCrMapping = 0

" cmd tab-completeion
set wildmode=longest,list
set wildmenu

" hilite braces
set showmatch
set matchtime=1

" sessions
set sessionoptions-=options
set sessionoptions+=localoptions
nmap <leader>sm :mks ~/.vim/sessions/
nmap <leader>sw :exe "mks! " . v:this_session<cr>
nmap <leader>so :so ~/.vim/sessions/

" colorcolumn
set colorcolumn=79
hi ColorColumn ctermbg=lightgrey guibg=#504040

" relativenumber
nmap <leader>nr :setl rnu<cr>
nmap <leader>nn :setl nu<cr>

set directory=~/.vim/tmp

" trailing whitespace trimming
autocmd BufWritePre * %s/\s\+$//e

set backspace=indent,eol,start

" bundles
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'

Bundle 'vim-coffee-script'
Bundle 'vim-stylus'
"Bundle 'Zenburn'
Bundle 'SuperTab'
Bundle 'scrooloose/nerdcommenter'
"Bundle 'fholgado/minibufexpl.vim'
Bundle 'digitaltoad/vim-jade'

filetype plugin indent on " required!

" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..

" spelling
set spelllang=ru_yo,en_us

" russian keymap
set keymap=russian-jcukenwin
set iminsert=0
set imsearch=0
highlight lCursor guifg=NONE guibg=Cyan

" python
let python_highlihgt_all = 1

" (x)html
let xml_use_xhtml = 1
let xml_no_html = 1

" less css
"function Lessc_compile ()
	"let nam = expand('<afile>:r')
	"exe "!lessc <afile> > ".nam.".css"
"endfunction
"au BufNewFile,BufRead *.less set filetype=less
"au FileType less set omnifunc=csscomplete#CompleteCSS
"au FileWritePost,BufWritePost *.less :call Lessc_compile()

" coffee-script
"au BufWritePost,FileWritePost *.coffee !coffee -c <afile>

" tabs <-> spaces
:command! -range=% -nargs=0 Tab2Space execute '<line1>,<line2>s#^\t\+#\=repeat(" ", len(submatch(0))*' . &ts . ')'
:command! -range=% -nargs=0 Space2Tab execute '<line1>,<line2>s#^\( \{'.&ts.'\}\)\+#\=repeat("\t", len(submatch(0))/' . &ts . ')'

